PREFIX ?= /app

install:
    install -Dm755 dist/SoberLauncher $(PREFIX)/bin/SoberLauncher
    install -Dm644 flatpak/org.taboulet.SoberLauncher.desktop $(PREFIX)/share/applications/org.taboulet.SoberLauncher.desktop
    install -Dm644 flatpak/SoberLauncher.svg $(PREFIX)/share/icons/hicolor/scalable/apps/org.taboulet.SoberLauncher.svg
